---
# tasks file for roles/install_ssl_for_jenkins
- name: Create volumes
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ nginx_certs_dir }}"
    - "{{ nginx_conf_dir }}"

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "{{ nginx_certs_dir }}/{{ domain }}.pem"

- name: Generate an OpenSSL CSR
  openssl_csr:
    path: "{{ nginx_certs_dir }}/{{ domain }}.csr"
    privatekey_path: "{{ nginx_certs_dir }}/{{ domain }}.pem"
    common_name: "{{ domain }}"

- name: Generate a Self Signed OpenSSL Certificate
  openssl_certificate:
    path: "{{ nginx_certs_dir }}/{{ domain }}.crt"
    privatekey_path: "{{ nginx_certs_dir }}/{{ domain }}.pem"
    csr_path: "{{ nginx_certs_dir }}/{{ domain }}.csr"
    provider: selfsigned

