---
- name: Install Docker with Jenkins
  hosts: all
  become: yes

  roles:
    - role: install_docker
    - role: install_jenkins_in_docker
    - role: install_ssl_for_jenkins
    - role: install_nginx_in_docker
