---
# tasks file for jenkins_in_docker

- name: Ping checking
  ping:

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add GPG Key
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add Docker repo
  apt_repository:
    update_cache: yes
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Docker install
  apt: 
    name: "{{ item }}"
    state: latest
  loop:
    - docker
    - docker-compose

