---
# tasks file for roles/install_nginx_in_docker
- name: Pull nginx image
  docker_image:
    name: nginx
    source: pull

- name: Run nginx in docker container
  docker_container:
    name: nginx
    image: nginx
    ports: 80:80

