---
# tasks file for roles/install_nginx_in_docker
- name: Pull nginx image
  docker_image:
    name: nginx
    source: pull

- name: Run nginx in docker container
  docker_container:
    name: nginx
    image: nginx
    state: started
    detach: yes
    exposed_ports: 
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /data/nginx/certs:/etc/nginx/certs
      - /data/nginx/conf/:/etc/nginx/conf.d/:ro
    links:
      - "MyJenkins:henrydev.pp.ua"

