---
# tasks file for roles/install_nginx_in_docker
- name: Copy nginx conf from template
  template:
    src: jenkins.conf
    dest: "{{ nginx_conf_dir}}/jenkins.conf"

- name: Pull nginx image
  docker_image:
    name: nginx
    source: pull

- name: Run nginx in docker container
  docker_container:
    name: nginx
    image: nginx
    state: started
    exposed_ports: 
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - "{{ nginx_certs_dir }}:/etc/nginx/certs"
      - "{{ nginx_conf_dir }}:/etc/nginx/conf.d"
#    links:
#      - "jenkins:henrydev.pp.ua"
 

