---
# tasks file for jenkins_in_docker

- name: Ping checking
  ping:

- name: OS update
  shell: apt update

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add GPG Key
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add Docker repo
  shell:
    cmd: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" | apt update

- name: Docker install
  apt: 
    name: "{{ item }}"
    state: latest
  loop:
    - docker
    - docker-compose

- name: Pull Jenkins image
  docker_image:
    name: jenkins/jenkins
    source: pull

- name: Run Jenkins in a Docker container
  docker_container:
    name: MyJenkins
    image: jenkins/jenkins
    state: started
    published_ports: 1234:8080

