---
# tasks file for roles/install_jenkins_in_docker
- name: Pull Jenkins image
  docker_image:
    name: jenkins/jenkins
    source: pull

- name: Run Jenkins in a Docker container
  docker_container:
    name: MyJenkins
    image: jenkins/jenkins
    state: started
    published_ports: 8080:8080
